name: Scheduled Semantic Release

on: 
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 1' # Every Monday at 00:00

jobs:
  semantic_release:
    runs-on: ubuntu-dind
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          path: telegraf
          token: ${{ secrets.PUSH_TOKEN }}

      - uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Semantic Release svtechnmaa telegraf
        uses: cycjimmy/semantic-release-action@v4
        id: semantic
        with:
          working_directory: ${{ github.workspace }}/telegraf
        env:
          GITHUB_TOKEN: ${{ secrets.PUSH_TOKEN }}
